StarWars/StarWars/Controllers/CatalogController.cs
using Microsoft.AspNetCore.Mvc;
using StarWars.Data.Enums;
using StarWars.Services;
using StarWars.ViewModels;

namespace StarWars.Controllers
{
	public class CatalogController : Controller
	{
		private readonly ICatalogService _catalogService;

		public CatalogController(ICatalogService catalogService)
		{
			_catalogService = catalogService;
		}

		[HttpGet]
		public async Task<IActionResult> Catalog(CatalogViewModel model, int? currentDateFrom, Gender? currentGender,
			List<int>? currentSelectedFilms, List<int>? currentSelectedPlanets,
			int? currentDateTo, int page = 1, int pageSize = 4)
		{
			if (model.dateFrom != null || model.dateTo != null || model.Gender != null ||
			    (model.SelectedFilms != null && model.SelectedFilms.Any()) ||
			    (model.SelectedPlanets != null && model.SelectedPlanets.Any()))
			{
				page = 1;
			}
			else
			{
				model.dateFrom = currentDateFrom;
				model.dateTo = currentDateTo;
				model.Gender = currentGender;
				model.SelectedFilms = currentSelectedFilms;
				model.SelectedPlanets = currentSelectedPlanets;
			}

			ViewBag.CurrentFilterDateFrom = model.dateFrom;
			ViewBag.CurrentFilterDateTo = model.dateTo;
			ViewBag.CurrentFilterGender = model.Gender;
			ViewBag.CurrentFilterSelectedFilms = model.SelectedFilms;
			ViewBag.CurrentFilterSelectedPlanets = model.SelectedPlanets;


			var catalogModel = await _catalogService.GetCatalog(model, page, pageSize);
			catalogModel.dateTo = model.dateTo;
			catalogModel.Gender = model.Gender;
			catalogModel.dateFrom = model.dateFrom;
			catalogModel.SelectedFilms = model.SelectedFilms;
			catalogModel.SelectedPlanets = model.SelectedPlanets;

			return View(catalogModel);
		}
	}
}

StarWars/StarWars/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en" class="h-100">
<head>
	<meta charset="utf-8"/>
	<meta name="viewport" content="width=device-width, initial-scale=1.0"/>
	<title>@ViewData["Title"] - StarWars</title>
	<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
	<link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
	<link rel="stylesheet" href="~/StarWars.styles.css" asp-append-version="true"/>

	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-select@1.13.14/dist/css/bootstrap-select.min.css">

	<!-- Latest compiled and minified JavaScript -->



	
</head>
<body class="d-flex flex-column h-100">
<header>
	<nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
		<div class="container-fluid">
			<a class="navbar-brand" asp-area="" asp-controller="Catalog" asp-action="Catalog">StarWars</a>
			<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
			        aria-expanded="false" aria-label="Toggle navigation">
				<span class="navbar-toggler-icon"></span>
			</button>
			<div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
				<ul class="navbar-nav flex-grow-1">
					<li class="nav-item">
						<a class="nav-link text-dark" asp-area="" asp-controller="Catalog" asp-action="Catalog">Каталог персонажей</a>
					</li>
				</ul>
				<partial name="_LoginPartial"/>
			</div>
		</div>
	</nav>
</header>
<div class="container shadow flex-shrink-0 pt-3">
	@if (@TempData["ErrorMessage"] != null)
	{
		<div class="card bg-danger mb-4">
			<h5 class="d-flex justify-content-center">@TempData["ErrorMessage"]</h5>
		</div>
	}
	
	<div class="d-flex">
		<a class="btn btn-outline-secondary me-1" asp-action="Catalog" asp-controller="Catalog">Каталог</a>
		@if (User.Identity.IsAuthenticated)
		{
			<a class="btn btn-outline-secondary" asp-action="CreateHero" asp-controller="Hero">Добавить персонажа</a>
		}
	</div>

	<main role="main" class="pb-3 mt-4">
		@RenderBody()
	</main>
</div>

<footer class="border-top footer text-muted mt-auto bg-light pt-3 pb-3">
	<div class="container">
		&copy; @DateTime.Now.Year
	</div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap-select@1.14.0-beta2/dist/js/bootstrap-select.min.js"></script>
	<script src="https://kit.fontawesome.com/f93a4357e7.js" crossorigin="anonymous"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>